# Generated by Django 5.1 on 2024-09-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0003_remove_note_label_note_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='bg_color',
            field=models.CharField(default='white', max_length=50),
        ),
    ]
