# Generated by Django 5.1 on 2024-09-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0004_alter_note_bg_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='collaborators',
        ),
        migrations.AddField(
            model_name='note',
            name='collaborators',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
