# Generated by Django 5.1 on 2024-09-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0005_remove_note_collaborators_note_collaborators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='labels',
            field=models.ManyToManyField(blank=True, default=[], related_name='note_labels', to='notes_app.label'),
        ),
    ]
