# Generated by Django 5.1 on 2024-09-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0007_alter_note_collaborators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='collaborators',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
